env:
  global:
    - COMMIT_AUTHOR_EMAIL: arash.fattahzade@carrene.com
language: python
dist: trusty
python: "3.6"
branches:
  only:
  - master
  - develop
  - nightly
  - /^v([1-9]\d*!)?(0|[1-9]\d*)(\.(0|[1-9]\d*))*((a|b|rc)(0|[1-9]\d*))?(\.post(0|[1-9]\d*))?(\.dev(0|[1-9]\d*))?$/
addons:
  apt:
    sources:
      - precise-pgdg-9.5
    packages:
      - postgresql-9.5
      - postgresql-contrib-9.5
      - libpq-dev
  postgresql: 9.5

services:
  - redis-server

install: ./scripts/travis-install.sh
script: coverage run --source jaguar $(which nosetests)
after_success: travis_retry coveralls
